import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';
import { Colors } from './Colors';

export const LightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: Colors.light.primary,
    onPrimary: '#ffffff',
    primaryContainer: Colors.light.primaryContainer,
    onPrimaryContainer: Colors.light.text,
    secondary: Colors.light.secondary,
    onSecondary: '#ffffff',
    secondaryContainer: Colors.light.secondaryContainer,
    onSecondaryContainer: Colors.light.text,
    tertiary: Colors.light.tertiary,
    onTertiary: '#ffffff',
    tertiaryContainer: Colors.light.tertiaryContainer,
    onTertiaryContainer: Colors.light.text,
    error: Colors.light.error,
    onError: '#ffffff',
    errorContainer: Colors.light.errorContainer,
    onErrorContainer: Colors.light.text,
    background: Colors.light.background,
    onBackground: Colors.light.text,
    surface: Colors.light.surface,
    onSurface: Colors.light.text,
    surfaceVariant: Colors.light.surfaceVariant,
    onSurfaceVariant: Colors.light.text,
    outline: Colors.light.outline,
    outlineVariant: Colors.light.outlineVariant,
    shadow: Colors.light.shadow,
    scrim: Colors.light.scrim,
    inverseSurface: Colors.light.inverseSurface,
    inverseOnSurface: Colors.light.inverseOnSurface,
    inversePrimary: Colors.light.inversePrimary,
    elevation: Colors.light.elevation,
  },
  roundness: 8,
};

export const DarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: Colors.dark.primary,
    onPrimary: '#ffffff',
    primaryContainer: Colors.dark.primaryContainer,
    onPrimaryContainer: Colors.dark.text,
    secondary: Colors.dark.secondary,
    onSecondary: '#ffffff',
    secondaryContainer: Colors.dark.secondaryContainer,
    onSecondaryContainer: Colors.dark.text,
    tertiary: Colors.dark.tertiary,
    onTertiary: '#ffffff',
    tertiaryContainer: Colors.dark.tertiaryContainer,
    onTertiaryContainer: Colors.dark.text,
    error: Colors.dark.error,
    onError: '#ffffff',
    errorContainer: Colors.dark.errorContainer,
    onErrorContainer: Colors.dark.text,
    background: Colors.dark.background,
    onBackground: Colors.dark.text,
    surface: Colors.dark.surface,
    onSurface: Colors.dark.text,
    surfaceVariant: Colors.dark.surfaceVariant,
    onSurfaceVariant: Colors.dark.text,
    outline: Colors.dark.outline,
    outlineVariant: Colors.dark.outlineVariant,
    shadow: Colors.dark.shadow,
    scrim: Colors.dark.scrim,
    inverseSurface: Colors.dark.inverseSurface,
    inverseOnSurface: Colors.dark.inverseOnSurface,
    inversePrimary: Colors.dark.inversePrimary,
    elevation: Colors.dark.elevation,
  },
  roundness: 8,
}; 